name: Merge develop into master

env:
  GIT_COMMITTER_EMAIL: actions@github.com
  GIT_COMMITTER_NAME: GitHub Actions

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git identity
        run: |
          git config --global user.email "${{ env.GIT_COMMITTER_EMAIL }}"
          git config --global user.name "${{ env.GIT_COMMITTER_NAME }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Merge develop into master
        run: |
          git checkout master
          git merge --no-ff --no-edit develop
          git push origin master
