name: Preview workflow

env:
  PACKAGE_NAME: purge-backups.deb

defaults:
  run:
    env:
      GIT_COMMITTER_EMAIL: actions@github.com
      GIT_COMMITTER_NAME: GitHub Actions
      RELEASE_COMMIT_MESSAGE: "Release of version"
      MERGE_MASTER_MESSAGE: "Merge branch 'master' into develop"
    shell: bash -eo pipefail {0}

on:
  push:
    branches:
      - develop

jobs:
  release-job:
    if: >
      !startsWith(github.event.head_commit.message, ${{ env.RELEASE_COMMIT_MESSAGE }})
      && github.event.head_commit.message != ${{ env.MERGE_MASTER_MESSAGE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up version
        id: version_step
        run: |
          VERSION=$(bash utils/version-manager.sh $(pwd) --release)
          echo "::set-output name=version::$VERSION"
      - name: Prepare
        run: |
          bash utils/builder.sh clean
          bash utils/builder.sh prepare
      - name: Package
        run: |
          bash utils/builder.sh package \
            -n "${{ env.PACKAGE_NAME }}"
      - name: Deploy
        run: |
          bash utils/builder.sh deploy \
            -u "${{ vars.REPOSITORY_PREVIEW_USERNAME }}" \
            -p "${{ secrets.REPOSITORY_PREVIEW_PASSWORD }}" \
            -r "${{ vars.REPOSITORY_PREVIEW_URL }}" \
            -n "${{ env.PACKAGE_NAME }}"
      - name: Commit and tag release changes
        run: |
          VERSION=${{ steps.version_step.outputs.version }}
          git add .
          git commit -m "Release of version $VERSION"
          git tag "v$VERSION"
          git push origin develop
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: Preview
          path: |
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
